### ISSUE TITLE
【不具合】ゲーム起動時に想定していない画面が映る

### ISSUE THREAD

**Issue by 2127002** [GTM106/BalloonGame#199]
## 現在の挙動
ゲーム開始時のタイトル画面遷移のトランジションに入る前に、一瞬だけゲーム画面が映ります。

## 想定する挙動
ゲーム開始時は暗転から開始します。手法は問いません、明度を下げて暗くしておいてもいいですし、黒画面のUIを事前に配置しておいても構いません。具体的な黒の程度は、スプラッシュスクリーンの背景色に合わせてください。

**Comment by 2127002** [comment]
![image](https://github.com/GTM106/BalloonGame/assets/104291548/41524d17-89fb-4206-baa6-3f9d09dc8ad7)

スプラッシュスクリーンの背景色はここから確認できます

**Comment by GTM106** [comment]
#204 により大筋は解決したはずです。しかし、シーン切り替え時はロードの具合によりバグってしまうため要修正になっています。
