### ISSUE TITLE
【不具合】水中でジャンプすると動けなくなる

### ISSUE THREAD

**Issue by 2127002** [GTM106/BalloonGame#208]
## 現在の挙動
水中でジャンプを行うと、落下モーションを取ったまま、移動不能状態に陥る場合がある。

## 想定される挙動
水中でジャンプを行っても移動不能に陥らない。

**Comment by GTM106** [comment]
どのシーンのどこの水で再現しますか？

**Comment by 2127002** [comment]
mainのoceanで発生します
