### ISSUE TITLE
【不具合】風船挙動バグ

### ISSUE THREAD

**Issue by Harmony82** [GTM106/BalloonGame#88]
### バグ内容
頭の風船の挙動、風船の空気量の変化にバグがあります。
### 再現方法
空気を入れている状態で空気栓のインタラクトエリア内に侵入すると空気の減少が止まります。その状態でインタラクトエリアから出ると空気が入った状態でふうせんが垂れます。プッシュすれば通常の挙動に戻ります。
### 正しい処理
空気栓のインタラクトエリア内でも膨らませることができないだけで通常の挙動です。継続して空気を減少してください。

**Comment by GTM106** [comment]
#86 にて空気栓から出た時に風船が垂れるバグは解決しています。

しかし、縮まないバグは解決していないためそちらのみ修正します。

上記により担当者から @yuto-0122 を外します
